### ISSUE TITLE
expose the connector via REST API of Kafka Connect

### ISSUE THREAD

**Issue by kyumarss** [jcustenborder/kafka-connect-rabbitmq#15]
The connector is currently run/tested via command line.
Exposing it via Kafka Connect's REST API can make it more self-contained and simplify its use.

**Comment by jcustenborder** [comment]
@kyumarss The rest interface is just a part of Kafka Connect. For testing I use standalone mode because it's more conducive to command line testing. Start the process wait for debugger, etc. This connector will work just fine in distributed mode which is configured via the rest interface. Any connector can be configured by the rest interface.
